### PR TITLE
remove model-optimizer and calls to high_resolution_clock::now on inference

### PR DESCRIPTION
**Pull request by camilo-celis**

### CODE REVIEW

**Comment by steve-pexip** [comment]
Looks plausible enough.  Can you say *why* you're making the changes as well please?

**Comment by camilo-celis** [comment]
@steve-pexip thanks for having a look, and sure! I will add them to the changelog then. or is that is not needed? anyhow, basically, the reasons are:
- model-optimizer is an unused feature for us, no real reason other than reducing the size of the package and perhaps reducing compilation time. we could very well keep it. 
- the removal of this PERF macro was needed due to https://github.com/pexip/mcu/issues/34030. Basically we noticed that a significant amount of CPU cycles were spent simply looking at the clock. This feature is useful, but only if we ever wanted to debug a ML model loaded to OpenVINO. This computation of running time is executed for every single node on a ML model which can be quite a large number! 
ref: https://github.com/pexip/os-openvino/blob/84f6577c1bf62c7fdaf054931674ef3ad63475fb/inference-engine/src/mkldnn_plugin/mkldnn_graph.cpp#L818C1-L818C1

**Comment by steve-pexip** [comment]
> @steve-pexip thanks for having a look, and sure! I will add them to the changelog then. or is that is not needed? anyhow, basically, the reasons are:
> 
> * model-optimizer is an unused feature for us, no real reason other than reducing the size of the package and perhaps reducing compilation time. we could very well keep it.
> * the removal of this PERF macro was needed due to [mlvad: overly optimistic load token count mcu#34031](https://github.com/pexip/mcu/issues/34031). Basically we noticed that a significant amount of CPU cycles were spent simply looking at the clock. This feature is useful, but only if we ever wanted to debug a ML model loaded to OpenVINO. This computation of running time is executed for every single node on a ML model which can be quite a large number!
>   ref: https://github.com/pexip/os-openvino/blob/84f6577c1bf62c7fdaf054931674ef3ad63475fb/inference-engine/src/mkldnn_plugin/mkldnn_graph.cpp#L818C1-L818C1

Cool! Just a quick summary of those in the changelog and commit log would be good, so we have them for future generations. :-)

**Comment by camilo-celis** [comment]
Force pushed a change to the commit message and changelog :)

**Review by steve-pexip — APPROVED** [review]
Looks great now, thanks!

**Pull request merged**
